### ISSUE TITLE
Support plain text attachments for Gemini

### ISSUE THREAD

**Issue by i-serebryakov07** [epam/ai-dial-adapter-vertexai#100]
Hello,

According to [gemini documentation](https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python#plain_text_formats) it supports various plan text formats in attachments (.txt, .json e.t.c.).

Could you please add these types to the [gemini chat adapter](https://github.com/epam/ai-dial-adapter-vertexai/blob/55d44cc1eb74fda165e840e65fe4de9d161e3272/aidial_adapter_vertexai/chat/gemini/processors.py)?

**Comment by adubovik** [comment]
@i-serebryakov07 the fix has been merged to the development. Thanks for filing the issue.
