### ISSUE TITLE
Add unit tests for system prompt messages

### ISSUE THREAD

**Issue by roman-romanov-o** [epam/ai-dial-adapter-vertexai#123]
Cover such cases with system prompt with unit tests

https://github.com/epam/ai-dial-adapter-vertexai/issues/119

**Comment by Puzer** [comment]
Based on [this](https://github.com/epam/ai-dial-adapter-vertexai/blob/f60c1857687d4de2a49d778e8c98ca612c083fe0/aidial_adapter_vertexai/chat/gemini/prompt/gemini_1_0_pro.py#L58) I see that adapter replaces system message with user message and concat them

It's a significant change and might lead to unexpected behaviour of LLM and degradated accuracy of model's output

I would suggest to review the approach

**Comment by adubovik** [comment]
@Puzer The system instructions have been fully supported in https://github.com/epam/ai-dial-adapter-vertexai/pull/137

I am closing the issue as not relevant anymore.
