### ISSUE TITLE
Support tools for Gemini PRO 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-adapter-vertexai#49]

**Comment by adubovik** [comment]
Find the examples of function calling in the notebooks ([1](https://codelabs.developers.google.com/codelabs/gemini-function-calling#10), [2](https://github.com/google-gemini/cookbook/blob/main/examples/Agents_Function_Calling_Barista_Bot.ipynb)) and API in the [documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini#gemini-1.0-pro-vision).
